# Generated by Django 2.0.2 on 2018-02-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('complete', models.BooleanField(default='false')),
                ('private_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
    ]
